version: '3'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=backstage
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    ports:
      - 5432:5432
    restart: always
    network_mode: host
  backstage:
    image: backstage:latest
    ports:
      - 7007:7007
      - 3000:3000
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    network_mode: host
volumes:
  backstage_data: