apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.component_id | dump}}
  description: ${{values.description | dump}}
  annotations:
    github.com/project-slug: ${{values.destination.owner + "/" + values.destination.repo}}
    backstage.io/techdocs-ref: dir:.
  links:
    - url: https://vuejs.org/
      title: Vue.js Koslog
      icon: site
  tags:
    - website
    - vue
spec:
  type: website
  lifecycle: experimental
  owner: ${{values.owner | dump}}