apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.name | dump}}
  description: ${{values.description | dump}}
  annotations:
    github.com/project-slug: ${{values.destination.owner + "/" + values.destination.repo}}
    backstage.io/managed-by-location: https://github.com/officialsamtech/nodejs-app/blob/main/catalog-info.yaml
    backstage.io/techdocs-ref: url:https://github.com/officialsamtech/nodejs-app/tree/main
spec:
  type: documentation
  lifecycle: experimental
  owner: ${{values.owner | dump}}